name: podiya
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_spinkit: "^5.0.0"
  firebase_auth: ^1.1.4
  flutter_auth_buttons: ^0.10.0
  google_sign_in: ^5.0.2
  firebase_core: ^1.1.1
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  json_serializable: ^4.1.1
  cloud_firestore: ^2.1.0
  firebase_storage: ^8.0.6
  provider: ^5.0.0
  flutter_cupertino_localizations: ^1.0.1
  dropdown_search: ^0.6.1
  flutter_tags: ^1.0.0-nullsafety.1
  multi_select_flutter: ^4.0.0
  intl_phone_number_input: ^0.7.0+2
  multi_image_picker: ^4.8.0
  curved_navigation_bar: ^0.4.0-nullsafety.0
  modal_bottom_sheet: ^2.0.0
  flutter_iconpicker: ^3.0.0
  smart_select: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  mobx_codegen: ^2.0.1+3

flutter:
  uses-material-design: true
  assets:
    - images/
