name: podiya
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: "^4.1.2"
  firebase_auth: ^1.0.1
  flutter_auth_buttons: ^0.10.0
  google_sign_in: ^4.5.3
  firebase_core: ^1.0.1
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  json_serializable: ^3.5.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  provider: ^5.0.0
  flutter_cupertino_localizations: ^1.0.1
  dropdown_search: ^0.4.8
  flutter_tags: "^0.4.9+1"
  multi_select_flutter: ^3.1.6
#  intl_phone_number_input: ^0.6.0
  multi_image_picker: ^4.8.0
  curved_navigation_bar: ^0.3.7
  modal_bottom_sheet: ^2.0.0
  flutter_iconpicker: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.5
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - images/
